; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "Mandrigo CMS"
!define PRODUCT_VERSION "0.7.0_dev"
!define PRODUCT_PUBLISHER "Mandrigo CMS Group"
!define PRODUCT_WEB_SITE "http://mandrigo.org"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define MG_DROOT_DIR $8
!define MG_EXT_DIR $9

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "C:\Documents and Settings\wijesek\Desktop\mandrigo-core\license.txt"
; Components page
!insertmacro MUI_PAGE_COMPONENTS
; Core Document Root page
!define MUI_DIRECTORYPAGE_VARIABLE ${MG_DROOT_DIR}
!define MUI_PAGE_HEADER_TEXT "Mandrigo CMS Core Document Root"
!define MUI_PAGE_HEADER_SUBTEXT ""
!define MUI_DIRECTORYPAGE_TEXT_TOP "Please select the Apache or IIS document root where you would like the mandrigo CMS core to be installed to."
!define MUI_DIRECTORYPAGE_TEXT_DESTINATION "Document Root"
!define MUI_DIRECTORYPAGE_VERIFYONLEAVE
!insertmacro MUI_PAGE_DIRECTORY
; External Root page
!define MUI_DIRECTORYPAGE_VARIABLE ${MG_EXT_DIR}
!define MUI_PAGE_HEADER_TEXT "Mandrigo CMS External Directory"
!define MUI_PAGE_HEADER_SUBTEXT ""
!define MUI_DIRECTORYPAGE_TEXT_TOP "Please select a directory that is external to your webserver."
!define MUI_DIRECTORYPAGE_TEXT_DESTINATION "External Directory"
!define MUI_DIRECTORYPAGE_VERIFYONLEAVE
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_SHOWREADME "$INSTDIR\htdocs\changelog.txt"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Spanish"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "mandrigo-0.7.0_dev.exe"
InstallDir "C:\www\"
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Section "Mandrigo Core" SEC01
  SetOutPath "${MG_DROOT_DIR}"
  SetOverwrite try
  File "C:\Documents and Settings\wijesek\Desktop\mandrigo-core\www\changelog.txt"

SectionEnd

Section "Mandrigo Admin" SEC02


SectionEnd

Section "Mandrigo Login Manager" SEC03


SectionEnd

Section "Mandrigo Packages" SEC04


SectionEnd

Section -AdditionalIcons
  SetOutPath ${MG_EXT_DIR}
  WriteIniStr "${MG_EXT_DIR}\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateDirectory "$SMPROGRAMS\Mandrigo CMS"
  CreateShortCut "$SMPROGRAMS\Mandrigo CMS\Website.lnk" "${MG_EXT_DIR}\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\Mandrigo CMS\Uninstall.lnk" "${MG_EXT_DIR}\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "${MG_EXT_DIR}\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "${MG_EXT_DIR}\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

; Section descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC01} "Mandrigo CMS Core"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC02} "Mandrigo CMS Admin Section"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC03} "Mandrigo CMS Login Router"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC04} "Mandrigo CMS Packages"
!insertmacro MUI_FUNCTION_DESCRIPTION_END


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "${MG_EXT_DIR}\${PRODUCT_NAME}.url"

  Delete "$SMPROGRAMS\Mandrigo CMS\Uninstall.lnk"

  RMDir "$SMPROGRAMS\Mandrigo CMS"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  SetAutoClose true
SectionEnd